FROM node:22-alpine

WORKDIR /app

# Copie des fichiers de dépendances
COPY package*.json ./
COPY tsconfig.json ./

# Installation des dépendances
RUN npm ci --only=production

# Copie du code source
COPY . . 

RUN npx tsc --outDir dist || true  # Force la sortie dans dist/

# Exposition du port
EXPOSE 4002

# Commande de démarrage
CMD ["node", "dist/index.js"]